#!/bin/bash

env

/usr/sbin/sshd

IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "Container IP=$IP"

# Update DNS
#curl -X DELETE http://$DNS_SERVER/dnsmasq-rest-api/zones/myZone
#curl -X POST http://$DNS_SERVER/dnsmasq-rest-api/zones/myZone/$PUBLIC_IP/$HOSTNAME
curl -X POST http://$DNS_SERVER/dnsmasq-rest-api/zones/myZone/$IP/$HOSTNAME
curl -X POST http://$DNS_SERVER/dnsmasq-rest-api/reload

# Start Spark Worker
echo "starting Spark Worker"
#ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
$SPARK_HOME/sbin/start-slave.sh 1 spark://$SPARK_MASTER_IP:$SPARK_MASTER_PORT

while [ 1 ];
do
	tail -f $SPARK_HOME/logs/*.out
        sleep 10
done